### ISSUE TITLE
Where clause seems to cause issues with parameter bag

### ISSUE THREAD

**Issue by atlantafawkes** [jamesfer/cypher-query-builder#42]
We are using the `.where()` method to fetch nodes like so:
`existingDataQuery.match([
    node('a', Attribute.getLabel()),
    InstanceValue.getAttributeRelationship(false),
    InstanceValue.getEmptyNode('iv')
])
.where({ 'ID(a)': attribute.id })
.return(['iv']).limit(1);`

We were noticing that there were no results returned for this query (even though we should see something).  Running `.toString()` seems to return the correct query:
`MATCH (a:Attribute)<-[:IS_VALUE_OF]-(iv:InstanceValue)
WHERE ID(a) = $idA
RETURN iv
LIMIT 1;`

When we run `.interpolate()` to see the parameters dropped in we see a problem:
`MATCH (a:Attribute)<-[:IS_VALUE_OF]-(iv:InstanceValue)
WHERE ID(a) = 9882
RETURN iv
LIMIT 1;`

The number value on the end of the parameter bag property name seems to be left at the end of the `id` parameter.  See the attached images for an example.
<img width="407" alt="example tostring" src="https://user-images.githubusercontent.com/15327556/43203247-b60888c6-8feb-11e8-96de-acc92d4eb1c1.png">
<img width="577" alt="parameter bag" src="https://user-images.githubusercontent.com/15327556/43203248-b6160370-8feb-11e8-9c8f-65f75dabe288.png">
<img width="405" alt="incorrect parameter value" src="https://user-images.githubusercontent.com/15327556/43203325-e9ecaaf0-8feb-11e8-9a84-2490f18a8e59.png">

**Comment by jamesfer** [comment]
Hi, thanks for reporting this, I'm sorry for the delayed reply.

I've confirmed a bug in the `.interpolate()` function and there is a fix that will be merged shortly. However this actual issue is caused by a bigger bug with the `WHERE` clause which is that multiple calls to `.build()` will repeatedly add clauses to the parameter bag, hence why you have 3 different `idA` parameters in your second screenshot. I'm currently looking into this and should have a fix out at the end of the week 🤞 .

**Comment by atlantafawkes** [comment]
Thanks @jamesfer !  We got around it by using `.raw()` - but now we can use `where` like normal human beings 😄.  I appreciate your time into this project.  It has worked well for us!

**Comment by atlantafawkes** [comment]
Ok, will do.  Thanks again!
