### ISSUE TITLE
Using Date results in Neo4jError

### ISSUE THREAD

**Issue by Fohlen** [jamesfer/cypher-query-builder#52]
Heya!
Using the JavaScript `Date` primitive results in the following error for me:

```
{ Neo4jError: Property values can only be of primitive types or arrays thereof

    at captureStacktrace (/Users/berger/workspace/eventzimmer/api/node_modules/neo4j-driver/lib/v1/result.js:200:15)
    at new Result (/Users/berger/workspace/eventzimmer/api/node_modules/neo4j-driver/lib/v1/result.js:73:19)
    at Session._run (/Users/berger/workspace/eventzimmer/api/node_modules/neo4j-driver/lib/v1/session.js:116:14)
    at Session.run (/Users/berger/workspace/eventzimmer/api/node_modules/neo4j-driver/lib/v1/session.js:95:19)
    at n.run (/Users/berger/workspace/eventzimmer/api/node_modules/cypher-query-builder/dist/index.js:1:23282)
    at n.<anonymous> (/Users/berger/workspace/eventzimmer/api/node_modules/cypher-query-builder/dist/index.js:1:8774)
    at e (/Users/berger/workspace/eventzimmer/api/node_modules/cypher-query-builder/dist/index.js:1:7976)
    at Object.next (/Users/berger/workspace/eventzimmer/api/node_modules/cypher-query-builder/dist/index.js:1:7311)
    at /Users/berger/workspace/eventzimmer/api/node_modules/cypher-query-builder/dist/index.js:1:7220
    at new Promise (<anonymous>)
  code: 'Neo.ClientError.Statement.TypeError',
  name: 'Neo4jError' }
```

My corresponding code looks like:
```
      let query = new cypher.Query(db)
      query.create([
        cypher.node(event.name, 'Event'),
        cypher.relation('out', ['StartsAt'], { date: event.date }),
        cypher.node(event.location.name, 'Location')
      ])
```

whereas `event.date` is a JavaScript date `event.date instanceof Date`.
The resulting query looks like:
```
CREATE (commodi:Event)-[:StartsAt $conditions]->(tenetur:Location);
```

What needs to be done in order to use Date's with this query builder?

**Comment by jamesfer** [comment]
The issue is because Neo4j only allows certain types of values to be stored as properties on a node and this package does not current support automatically converting Javascript Date objects into a format accepted by Neo4j.

Probably the easiest way to rewrite your query is:

      query.create([
        cypher.node(event.name, 'Event'),
        cypher.relation('out', 'relation', ['StartsAt']),
        cypher.node(event.location.name, 'Location')
      ])
        .raw('WHERE relation.date = datetime($date)', { date: event.date.toISOString() })

`event.date.toISOString()` creates a Neo4J compatible string like `2018-09-07T00:25:35.425Z`, however, if you're looking to find all events that are at a particular time, that might be too precise for you as it includes fractions of a second.
The Cypher `datetime` function takes a string representation of a date and converts it to Neo4j's internal representation of a date. There is more information about how Neo4j handles dates [here](https://neo4j.com/docs/developer-manual/current/cypher/syntax/temporal/)

I know the current work around isn't that nice, I'll starting thinking about how we can support this more easily in the future. Let me know if there is a particular way you think this could be designed to make it easiest for you.

**Comment by Fohlen** [comment]
Hey! That's what I assumed so far. Thanks for telling me about the `.raw` workaround. Anyhow. Can I help to make this happen?

**Comment by purplemana** [comment]
I cheated a bit for this...

    new Query()
          .match([
            node("n"),
            relation("out", "c", RelationLabels.Created),
            node("m", undefined, { id })
          ])
          .return({ "datetime(c.on)": "on" });

However, the returned results from the transformer are still in the Neo4J Date format. @jamesfer Is there a way to have them parsed in a simple ISO format? Thanks.

**Comment by jamesfer** [comment]
@purplemana, sorry I've been out of state for the past couple weeks so didn't get a chance to have a look at this. 
Definitely want to support transforming time values as well. However, I was going to rewrite the transformation code soon anyway so I might incorporate it into those changes.

**Comment by purplemana** [comment]
Ok. Anyways I managed to unblock myself by using `toString` in my cypher queries to convert datetime to iso strings.

**Comment by purplemana** [comment]
> I was going to rewrite the transformation code soon anyway so I might incorporate it into those changes.
👍 
While you are at it, please review the TS usage. The current implementation is not correctly representing the parsed data.

**Comment by Fohlen** [comment]
`toString` seems to be satisfying.
